### PR TITLE
Update explorer to 2024-07-22

### PR DESCRIPTION
**Pull request by bdon**
* fix JSX warning by adding key= to Fragment
* schema change boundary -> division_boundary

### CODE REVIEW

**Comment by bdon** [comment]
May need a manual merge with https://github.com/OvertureMaps/io-site/pull/97

**Comment by eti7075** [comment]
@bdon Just confirming, this new pmtiles url contains the address theme?

**Comment by bdon** [comment]
new address theme is included: `https://d3c1b7bog2u1nn.cloudfront.net/2024-07-22/addresses.pmtiles`, so you don't need to special-case the URL for addresses

**Comment by Bonkles** [comment]
#97 just got merged- we do indeed have a minor conflict here. @bdon can you resolve?

**Comment by bdon** [comment]
@eti7075 's commit already incorporates these changes, so I can close this PR!

**Pull request closed without merging**
